---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]    
  customize:
    natdnshostresolver1: "on"

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  # - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[rails-passenger::default]
    attributes:
